#include "BIT_MATH.h"
#include "STD_TYPES.h"

#include "DIO_interface.h"
#include "Timer1_Config.h"
#include "Timer1_interface.h"
#include "Timer1_private.h"
#include "Timer1_register.h"

void MTimer1_voidInit()
{
	/*Choose Compare Output Mode and Channel*/
#if TIMER1_COMPARE_OUTPUT_MODE_CHANNEL == TIMER1_CHANNEL_A


	//set PIN as OUTPUT
	MDIO_voidSetPinDirection(PORTD, PIN5, OUTPUT);

	#if (TIMER1_COMPARE_OUTPUT_MODE == TIMER1_NON_PWM_NORMAL_OPERATION || TIMER1_COMPARE_OUTPUT_MODE == TIMER1_FAST_PWM_NORMAL_OPERATION|| TIMER1_COMPARE_OUTPUT_MODE == TIMER1_PHASE_CORRECT_NORMAL_OPERATION)
		CLR_BIT(TCCR1A, TCCR1A_COM1A0);
		CLR_BIT(TCCR1A, TCCR1A_COM1A1);

	#elif (TIMER1_COMPARE_OUTPUT_MODE == TIMER1_NON_PWM_TOGGLE_ON_COMPARE || TIMER1_COMPARE_OUTPUT_MODE == TIMER1_FAST_PWM_TOGGLE_ON_COMPARE|| TIMER1_COMPARE_OUTPUT_MODE == TIMER1_PHASE_CORRECT_TOGGLE_ON_COMPARE)
		SET_BIT(TCCR1A, TCCR1A_COM1A0);
		CLR_BIT(TCCR1A, TCCR1A_COM1A1);

	#elif (TIMER1_COMPARE_OUTPUT_MODE == TIMER1_NON_PWM_CLEAR_ON_COMPARE || TIMER1_COMPARE_OUTPUT_MODE == TIMER1_FAST_PWM_CLEAR_ON_COMPARE|| TIMER1_COMPARE_OUTPUT_MODE == TIMER1_PHASE_CORRECT_CLEAR_ON_COMPARE)
		CLR_BIT(TCCR1A, TCCR1A_COM1A0);
		SET_BIT(TCCR1A, TCCR1A_COM1A1);

	#elif (TIMER1_COMPARE_OUTPUT_MODE == TIMER1_NON_PWM_SET_ON_COMPARE || TIMER1_COMPARE_OUTPUT_MODE == TIMER1_FAST_PWM_SET_ON_COMPARE|| TIMER1_COMPARE_OUTPUT_MODE == TIMER1_PHASE_CORRECT_SET_ON_COMPARE)
		SET_BIT(TCCR1A, TCCR1A_COM1A0);
		SET_BIT(TCCR1A, TCCR1A_COM1A1);

	#endif



#elif TIMER1_COMPARE_OUTPUT_MODE_CHANNEL == TIMER1_CHANNEL_B
		//set PIN as OUTPUT
			MDIO_voidSetPinDirection(PORTD, PIN4, OUTPUT);

	#if (TIMER1_COMPARE_OUTPUT_MODE == TIMER1_NON_PWM_NORMAL_OPERATION || TIMER1_COMPARE_OUTPUT_MODE == TIMER1_FAST_PWM_NORMAL_OPERATION|| TIMER1_COMPARE_OUTPUT_MODE == TIMER1_PHASE_CORRECT_NORMAL_OPERATION)
		CLR_BIT(TCCR1A, TCCR1A_COM1B0);
		CLR_BIT(TCCR1A, TCCR1A_COM1B1);

	#elif (TIMER1_COMPARE_OUTPUT_MODE == TIMER1_NON_PWM_TOGGLE_ON_COMPARE || TIMER1_COMPARE_OUTPUT_MODE == TIMER1_FAST_PWM_TOGGLE_ON_COMPARE||TIMER1_ COMPARE_OUTPUT_MODE == TIMER1_PHASE_CORRECT_TOGGLE_ON_COMPARE)
		SET_BIT(TCCR1A, TCCR1A_COM1B0);
		CLR_BIT(TCCR1A, TCCR1A_COM1B1);

	#elif (TIMER1_COMPARE_OUTPUT_MODE == TIMER1_NON_PWM_CLEAR_ON_COMPARE || TIMER1_COMPARE_OUTPUT_MODE == TIMER1_FAST_PWM_CLEAR_ON_COMPARE|| TIMER1_COMPARE_OUTPUT_MODE == TIMER1_PHASE_CORRECT_CLEAR_ON_COMPARE)
		SET_BIT(TCCR1A, TCCR1A_COM1B0);
		CLR_BIT(TCCR1A, TCCR1A_COM1B1);

	#elif (TIMER1_COMPARE_OUTPUT_MODE == TIMER1_NON_PWM_SET_ON_COMPARE || TIMER1_COMPARE_OUTPUT_MODE == TIMER1_FAST_PWM_SET_ON_COMPARE|| TIMER1_COMPARE_OUTPUT_MODE == TIMER1_PHASE_CORRECT_SET_ON_COMPARE)
		SET_BIT(TCCR1A, TCCR1A_COM1B0);
		SET_BIT(TCCR1A, TCCR1A_COM1B1);

	#endif

#else
	//error input
#endif

/*Choose Waveform Generation Mode*/
#if TIMER1_WAVE_GENERATION_MODE == TIMER1_NORMAL_MODE
	CLR_BIT(TCCR1A, TCCR1A_WGM10);
	CLR_BIT(TCCR1A, TCCR1A_WGM11);
	CLR_BIT(TCCR1B, TCCR1B_WGM12);
	CLR_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT_8_Bit_MODE
	SET_BIT(TCCR1A, TCCR1A_WGM10);
	CLR_BIT(TCCR1A, TCCR1A_WGM11);
	CLR_BIT(TCCR1B, TCCR1B_WGM12);
	CLR_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT_9_Bit_MODE
	CLR_BIT(TCCR1A, TCCR1A_WGM10);
	SET_BIT(TCCR1A, TCCR1A_WGM11);
	CLR_BIT(TCCR1B, TCCR1B_WGM12);
	CLR_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT_10_Bit_MODE
	SET_BIT(TCCR1A, TCCR1A_WGM10);
	SET_BIT(TCCR1A, TCCR1A_WGM11);
	CLR_BIT(TCCR1B, TCCR1B_WGM12);
	CLR_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_CTC_MODE_OCR1A
	CLR_BIT(TCCR1A, TCCR1A_WGM10);
	CLR_BIT(TCCR1A, TCCR1A_WGM11);
	SET_BIT(TCCR1B, TCCR1B_WGM12);
	CLR_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_8_Bit_MODE
	SET_BIT(TCCR1A, TCCR1A_WGM10);
	CLR_BIT(TCCR1A, TCCR1A_WGM11);
	SET_BIT(TCCR1B, TCCR1B_WGM12);
	CLR_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_9_Bit_MODE
	CLR_BIT(TCCR1A, TCCR1A_WGM10);
	SET_BIT(TCCR1A, TCCR1A_WGM11);
	SET_BIT(TCCR1B, TCCR1B_WGM12);
	CLR_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_10_Bit_MODE
	SET_BIT(TCCR1A, TCCR1A_WGM10);
	SET_BIT(TCCR1A, TCCR1A_WGM11);
	SET_BIT(TCCR1B, TCCR1B_WGM12);
	CLR_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_PWM_PHASE_FREQUENCY_CORRECT_MODE_ICR1
	CLR_BIT(TCCR1A, TCCR1A_WGM10);
	CLR_BIT(TCCR1A, TCCR1A_WGM11);
	CLR_BIT(TCCR1B, TCCR1B_WGM12);
	SET_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_PWM_PHASE_FREQUENCY_CORRECT_MODE_OCR1A
	SET_BIT(TCCR1A, TCCR1A_WGM10);
	CLR_BIT(TCCR1A, TCCR1A_WGM11);
	CLR_BIT(TCCR1B, TCCR1B_WGM12);
	SET_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT_MODE_ICR1
	CLR_BIT(TCCR1A, TCCR1A_WGM10);
	SET_BIT(TCCR1A, TCCR1A_WGM11);
	CLR_BIT(TCCR1B, TCCR1B_WGM12);
	SET_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT_MODE_OCR1A
	SET_BIT(TCCR1A, TCCR1A_WGM10);
	SET_BIT(TCCR1A, TCCR1A_WGM11);
	CLR_BIT(TCCR1B, TCCR1B_WGM12);
	SET_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_CTC_MODE_ICR1
	CLR_BIT(TCCR1A, TCCR1A_WGM10);
	CLR_BIT(TCCR1A, TCCR1A_WGM11);
	SET_BIT(TCCR1B, TCCR1B_WGM12);
	SET_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_MODE_ICR1
	CLR_BIT(TCCR1A, TCCR1A_WGM10);
	SET_BIT(TCCR1A, TCCR1A_WGM11);
	SET_BIT(TCCR1B, TCCR1B_WGM12);
	SET_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_MODE_OCR1A
	SET_BIT(TCCR1A, TCCR1A_WGM10);
	SET_BIT(TCCR1A, TCCR1A_WGM11);
	SET_BIT(TCCR1B, TCCR1B_WGM12);
	SET_BIT(TCCR1B, TCCR1B_WGM13);

#endif

/*Clock Select*/
#if TIMER1_SELECT_CLK == TIMER1_NO_CLK
CLR_BIT(TCCR1B, TCCR1B_CS10);
CLR_BIT(TCCR1B, TCCR1B_CS11);
CLR_BIT(TCCR1B, TCCR1B_CS12);

#elif TIMER1_SELECT_CLK == TIMER1_CLK_NO_PRESCALER
SET_BIT(TCCR1B, TCCR1B_CS10);
CLR_BIT(TCCR1B, TCCR1B_CS11);
CLR_BIT(TCCR1B, TCCR1B_CS12);

#elif TIMER1_SELECT_CLK == TIMER1_CLK_DIVIDED_BY_8
CLR_BIT(TCCR1B, TCCR1B_CS10);
SET_BIT(TCCR1B, TCCR1B_CS11);
CLR_BIT(TCCR1B, TCCR1B_CS12);

#elif TIMER1_SELECT_CLK == TIMER1_CLK_DIVIDED_BY_64
SET_BIT(TCCR1B, TCCR1B_CS10);
SET_BIT(TCCR1B, TCCR1B_CS11);
CLR_BIT(TCCR1B, TCCR1B_CS12);

#elif TIMER1_SELECT_CLK == TIMER1_CLK_DIVIDED_BY_256
CLR_BIT(TCCR1B, TCCR1B_CS10);
CLR_BIT(TCCR1B, TCCR1B_CS11);
SET_BIT(TCCR1B, TCCR1B_CS12);

#elif TIMER1_SELECT_CLK == TIMER1_CLK_DIVIDED_BY_1024
SET_BIT(TCCR1B, TCCR1B_CS10);
CLR_BIT(TCCR1B, TCCR1B_CS11);
SET_BIT(TCCR1B, TCCR1B_CS12);

#elif TIMER1_SELECT_CLK == TIMER1_CLK_ON_FALLING_EDGE
CLR_BIT(TCCR1B, TCCR1B_CS10);
SET_BIT(TCCR1B, TCCR1B_CS11);
SET_BIT(TCCR1B, TCCR1B_CS12);

#elif TIMER1_SELECT_CLK == TIMER1_CLK_ON_RISING_EDGE
SET_BIT(TCCR1B, TCCR1B_CS10);
SET_BIT(TCCR1B, TCCR1B_CS11);
SET_BIT(TCCR1B, TCCR1B_CS12);

#endif

}
void MTimer1_voidSetDutyCycle(u16 Copy_u16DutyCycleValue)
{

#if TIMER1_COMPARE_OUTPUT_MODE_CHANNEL == TIMER1_CHANNEL_A
	OCR1AL = Copy_u16DutyCycleValue;

#elif TIMER1_COMPARE_OUTPUT_MODE_CHANNEL == TIMER1_CHANNEL_A
	OCR1AL = Copy_u16CompareMatchValue;
#else
	//error
#endif
}

void MTimer1_voidSetICR(u16 Copy_u8MaxAngle)
{
	ICR1L = Copy_u8MaxAngle;
}



