#ifndef Timer0_CONFIG_H
#define Timer0_CONFIG_H

/*
 * Options:
 			1-TIMER0_NORMAL_MODE	2-TIMER0_PWM_MODE
 			3-TIMER0_CTC_MODE		4-TIMER0_FAST_PWM_MODE
 */
#define TIMER0_MODE		TIMER0_FAST_PWM_MODE
/*
 * Options:
			1- TIMER0_NO_CLK					2- TIMER0_CLK_NO_PRESCALER
			3- TIMER0_CLK_DIVIDED_BY_8			4- TIMER0_CLK_DIVIDED_BY_64
			5- TIMER0_CLK_DIVIDED_BY_256		6- TIMER0_CLK_DIVIDED_BY_1024
			7- TIMER0_CLK_ON_FALLING_EDGE		8- TIMER0_CLK_ON_RISING_EDGE
 */
#define TIMER0_SELECT_CLK	TIMER0_CLK_DIVIDED_BY_8

/*Hand analysis to set start point*/
#define TIMER0_PRELOAD_VALUE 	0

/*
 * Options:
 			1-COMPAR_MATCH_INTERRUPT_ENABLE
 			2-OVERFLOW_INTERRUPT_ENABLE
 */
#define TIMER0_INTERRUPT_ENABLE		COMPAR_MATCH_INTERRUPT_DISABLE


/*Options:
 *	1-TIMER0_NORMAL_MODE_FAST_PWM
	2-TIMER0_CLEAR_ON_COMPARE_FAST_PWM
	3-TIMER0_SET_ON_COMPARE_FAST_PWM
 */

#define TIMER0_FAST_PWM_MODE_SELECT 	TIMER0_CLEAR_ON_COMPARE_FAST_PWM

#define TIMER0_DESIRED_OVERFLOW		4

#endif
