#ifndef TIMER1_CONFIG_H
#define TIMER1_CONFIG_H

 /* Options:
			1- TIMER1_NO_CLK					2- TIMER1_CLK_NO_PRESCALER
			3- TIMER1_CLK_DIVIDED_BY_8			4- TIMER1_CLK_DIVIDED_BY_64
			5- TIMER1_CLK_DIVIDED_BY_256		6- TIMER1_CLK_DIVIDED_BY_1024
			7- TIMER1_CLK_ON_FALLING_EDGE		8- TIMER1_CLK_ON_RISING_EDGE
 	 */
#define TIMER1_SELECT_CLK	TIMER1_CLK_DIVIDED_BY_8

/*Options :
 * 1- TIMER1_CHANNEL_A
 * 2- TIMER1_CHANNEL_B
 */
#define TIMER1_COMPARE_OUTPUT_MODE_CHANNEL		TIMER1_CHANNEL_A

/*Options:
	1-TIMER1_NON_PWM_NORMAL_OPERATION			2-TIMER1_NON_PWM_TOGGLE_ON_COMPARE
	3-TIMER1_NON_PWM_SET_ON_COMPARE				4-TIMER1_NON_PWM_CLEAR_ON_COMPARE
	5-TIMER1_FAST_PWM_NORMAL_OPERATION			6-TIMER1_FAST_PWM_TOGGLE_ON_COMPARE
	7-TIMER1_FAST_PWM_SET_ON_COMPARE			8-TIMER1_FAST_PWM_CLEAR_ON_COMPARE
	9-TIMER1_PHASE_CORRECT_NORMAL_OPERATION		10-TIMER1_PHASE_CORRECT_TOGGLE_ON_COMPAR
	11-TIMER1_PHASE_CORRECT_SET_ON_COMPARE		12-TIMER1_PHASE_CORRECT_CLEAR_ON_COMPARE
  */
#define TIMER1_COMPARE_OUTPUT_MODE		TIMER1_FAST_PWM_CLEAR_ON_COMPARE

/*Options:
	1-TIMER1_NORMAL_MODE								2-TIMER1_PWM_PHASE_CORRECT_8_Bit_MODE
	3-TIMER1_PWM_PHASE_CORRECT_9_Bit_MODE				4-TIMER1_PWM_PHASE_CORRECT_10_Bit_MODE
	5-TIMER1_CTC_MODE_OCR1A								6-TIMER1_FAST_PWM_8_Bit_MODE
	7-TIMER1_FAST_PWM_9_Bit_MODE						8-TIMER1_FAST_PWM_10_Bit_MODE
	9-TIMER1_PWM_PHASE_FREQUENCY_CORRECT_MODE_ICR1		10-TIMER1_PWM_PHASE_FREQUENCY_CORRECT_MODE_OCR1A
	11-TIMER1_PWM_PHASE_CORRECT_MODE_ICR1				12-TIMER1_PWM_PHASE_CORRECT_MODE_OCR1A
	13-TIMER1_CTC_MODE_ICR1								14-TIMER1_FAST_PWM_MODE_ICR1
	15-TIMER1_FAST_PWM_MODE_OCR1A
 */
#define TIMER1_WAVE_GENERATION_MODE		TIMER1_FAST_PWM_MODE_ICR1

#endif
