#ifndef USART_PRIVATE_H
#define USART_PRIVATE_H
	
#define USART_ASYNCHROUNOUS_OPERATION	0
#define USART_SYNCHROUNOUS_OPERATION	1

#define USART_PARITY_MODE_DISABLE			0
#define USART_PARITY_MODE_EVEN_ENABLE		2
#define USART_PARITY_MODE_ODD_ENABLE		3

#define USART_STOP_BIT_SELECTION_ONE		0
#define USART_STOP_BIT_SELECTION_TWO		1

#define	USART_CHARACTER_SIZE_SELECTION_5_BIT	0
#define	USART_CHARACTER_SIZE_SELECTION_6_BIT    1
#define	USART_CHARACTER_SIZE_SELECTION_7_BIT    2
#define	USART_CHARACTER_SIZE_SELECTION_8_BIT    3
#define	USART_CHARACTER_SIZE_SELECTION_9_BIT    4

#define ENTER_PRESS		10

#endif



